.PHONY: clean All

All:
	@echo "----------Building project:[ oop10 - Debug ]----------"
	@cd "oop10" && "$(MAKE)" -f  "oop10.mk"
clean:
	@echo "----------Cleaning project:[ oop10 - Debug ]----------"
	@cd "oop10" && "$(MAKE)" -f  "oop10.mk" clean
