.PHONY: clean All

All:
	@echo "----------Building project:[ oop15 - Debug ]----------"
	@cd "oop15" && "$(MAKE)" -f  "oop15.mk"
clean:
	@echo "----------Cleaning project:[ oop15 - Debug ]----------"
	@cd "oop15" && "$(MAKE)" -f  "oop15.mk" clean
