.PHONY: clean All

All:
	@echo "----------Building project:[ oop12 - Debug ]----------"
	@cd "oop12" && "$(MAKE)" -f  "oop12.mk"
clean:
	@echo "----------Cleaning project:[ oop12 - Debug ]----------"
	@cd "oop12" && "$(MAKE)" -f  "oop12.mk" clean
