.PHONY: clean All

All:
	@echo "----------Building project:[ oop11 - Debug ]----------"
	@cd "oop11" && "$(MAKE)" -f  "oop11.mk"
clean:
	@echo "----------Cleaning project:[ oop11 - Debug ]----------"
	@cd "oop11" && "$(MAKE)" -f  "oop11.mk" clean
