.PHONY: clean All

All:
	@echo "----------Building project:[ oop7 - Debug ]----------"
	@cd "oop7" && "$(MAKE)" -f  "oop7.mk"
clean:
	@echo "----------Cleaning project:[ oop7 - Debug ]----------"
	@cd "oop7" && "$(MAKE)" -f  "oop7.mk" clean
