.PHONY: clean All

All:
	@echo "----------Building project:[ oop8 - Debug ]----------"
	@cd "oop8" && "$(MAKE)" -f  "oop8.mk"
clean:
	@echo "----------Cleaning project:[ oop8 - Debug ]----------"
	@cd "oop8" && "$(MAKE)" -f  "oop8.mk" clean
