.PHONY: clean All

All:
	@echo "----------Building project:[ oop2 - Debug ]----------"
	@cd "oop2" && "$(MAKE)" -f  "oop2.mk"
clean:
	@echo "----------Cleaning project:[ oop2 - Debug ]----------"
	@cd "oop2" && "$(MAKE)" -f  "oop2.mk" clean
